# permissions for end users to view certificates.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: certificate-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: certificate-operator
    app.kubernetes.io/part-of: certificate-operator
    app.kubernetes.io/managed-by: kustomize
  name: certificate-viewer-role
rules:
- apiGroups:
  - cert.dana.io
  resources:
  - certificates
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cert.dana.io
  resources:
  - certificates/status
  verbs:
  - get
