# permissions for end users to edit certificateconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: certificateconfig-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: certificate-operator
    app.kubernetes.io/part-of: certificate-operator
    app.kubernetes.io/managed-by: kustomize
  name: certificateconfig-editor-role
rules:
- apiGroups:
  - cert.dana.io
  resources:
  - certificateconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cert.dana.io
  resources:
  - certificateconfigs/status
  verbs:
  - get
